dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('sales/', views.sale_view, name='sale_list'),
    path('members/', views.user_profile_view, name='member_list' ),
    path('profile/<int:id>/', views.user_profile_detail_view, name='profile'),
    path('loans/', views.loanView, name='loan_list'),
    path('commision/', views.commisionView, name='commision_list'),
    path('products/', views.productView, name='product_list'),
    path('get-me/', views.getMeView, name='getme'),

    path('api/billing-profile-<int:id>/', views.json_user_billing_view, name='json_billing_profile'),
    path('api/commision-profile-<int:id>/', views.json_user_commision_view, name='json_commision_profile'),
    path('api/loan-profile-<int:id>/', views.json_user_loan_view, name='json_loan_profile'),
    path('api/application/', views.get_application_view, name='application'),
    path('api/products/', views.productJsonView, name='json_products'),
]

ppob_multipay/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from core import views as core_views
from dashboard import views as dashboard_views
from v2 import views as v2_view
from transaction import views as transac_view

from rest_framework_jwt.views import (
    obtain_jwt_token, refresh_jwt_token, verify_jwt_token
)

urlpatterns = [
    path('', v2_view.HomeView.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/custom-login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset-password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    path('activate/<slug:uidb64>/<slug:token>/', core_views.activate, name='activate'),
    path('activate-success/', core_views.activate_success, name='activate_success'),
    path('adminpanel/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('product/', include('product.urls')),
    path('profile/', include('userprofile.urls')),
    path('v2/', include('v2.urls')),
    
    path('trx-bulk-checking/', transac_view.bulk_update_trx),

    # INI HARUS DELETE KLO SUDAH GANTI HOST API
    path('api/profile/', include('userprofile.api.urls')),
    path('api/product/', include('product.api.urls')),
    path('api/transaction/', include('transaction.api.urls')),
    path('api/billing/', include('billing.api.urls')),
    path('api/payment/', include('payment.api.urls')),
    path('api/bankrecon/', include('bankrecon.api.urls')),
    path('api/withdraw/', include('witdraw.api.urls')),
    path('api/app/', include('api_production.api.urls')),

    path('jwt-token-auth/', obtain_jwt_token),
    path('jwt-token-refresh/', refresh_jwt_token),
    path('jwt-token-verify/', verify_jwt_token),
    # END DELETE
]

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

v2/urls.py
from django.urls import path

from . import views

app_nam = 'v2'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
]

dashboard/models.py
from django.db import models

from core.models import CommonBase

class Application(CommonBase):
    app_name = models.CharField(max_length=100)
    attach = models.FileField(upload_to='application/', blank=True, null=True)
    link = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return self.app_name

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import F, Q, Sum, Count, Value as V, Case, When, Max, Min
from django.db.models.functions import Coalesce, TruncDate, TruncMonth
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.contrib.postgres.search import SearchVector

from billing.models import (
    BillingRecord, CommisionRecord, LoanRecord
)
from userprofile.models import Profile
from core.decorators import (
    user_is_agen, user_is_related_agen
)
from product.models import (
    Product, Group
)

from .models import Application


def get_pagination(obj, n=10, page=1):
    page_list = Paginator(obj, n)
    try:
        bill_list = page_list.page(page)
    except PageNotAnInteger:
        bill_list = page_list.page(1)
    except EmptyPage:
        bill_list = page_list.page(page_list.page_range)

    return bill_list


# VIEW APPLICATION ON HOME PAGE
def get_application_view(request):
    data = dict()
    app_obj = Application.objects.latest('timestamp')
    data['html'] = render_to_string(
        'dashboard/includes/partial-application.html', 
        {'app': app_obj},
        request=request
    ) 
    return JsonResponse(data)


# INDEX
@login_required
def index(request):
    commision_objs = CommisionRecord.objects.filter(
        agen = request.user, is_delete=False
    )

    content = {
        'commision_list': commision_objs[:5]
    }
    return render(request, 'dashboard/index.html', content)


# SALE VIEW
@login_required
def sale_view(request):
    """
        Sale for related user
        Pagination
        Search by customer
    """
    page = request.GET.get('page', None)
    q = request.GET.get('q', None)

    bill_objs = BillingRecord.objects.filter(
        sequence = 1
    ).filter(
        Q(instansale_trx__isnull=False) | Q(ppobsale_trx__isnull=False)
    )

    if not request.user.is_superuser:
        # Sales for related user
        bill_objs = bill_objs.filter(
            user=request.user
        )

    if q:
        # Sale search
        bill_objs = bill_objs.annotate(
            search = SearchVector(
                'instansale_trx__customer', 'ppobsale_trx__customer'
            )
        ).filter(search = q)

    # Pagination
    bill_list = get_pagination(bill_objs, n=20, page=page)

    content = {
        'bill_list': bill_list,
        'q': q
    }
    return render(request, 'dashboard/pg-sale.html', content)


# PRODUCT  VIEW
@login_required
def productView(request):
    group_objs = Group.objects.filter(
        active = True
    )
    product_objs = Product.objects.filter(
        group__code = 'PULSA', operator__code='TSEL'
    )
    content = {
        'group_list': group_objs,
        'product_list': product_objs,
    }
    return render(request, 'dashboard/pg-product.html', content)


# PRODUCT JS VIEW
@login_required
def productJsonView(request):
    data = dict()
    op = request.GET.get('op', 1)
    gr = request.GET.get('gr', 1)

    product_objs = Product.objects.filter(
        group_id=gr, operator_id=op
    )
    content = {
        'product_list': product_objs
    }
    data['html'] = render_to_string(
        'dashboard/includes/partial-product-list.html',
        content, request=request
    )
    return JsonResponse(data)


@login_required
def getMeView(request):
    return render(request, 'dashboard/pg-getme.html')

# LOAN VIEW
@login_required
@user_is_agen
def loanView(request):
    """
        Agen required
        Loan of member
        Loan Search
        pagination
    """
    page = request.GET.get('page', 1)

    loan_objs = LoanRecord.objects.filter(
        agen = request.user
    )

    loan_pages = get_pagination(loan_objs, 20, page)
    content = {
        'loan_list': loan_pages
    }

    return render(request, 'dashboard/pg-loan.html', content)


# COMMISISON VIEW
@login_required
@user_is_agen
def commisionView(request):
    """
        Commision agen
        Pagination
    """
    page = request.GET.get('page', 1)

    commision_objs = CommisionRecord.objects.filter(
        agen = request.user
    )

    resume_commision = commision_objs.aggregate(
        commision = Coalesce(
            Sum(F('debit')-F('credit')), V(0)
        )
    ) 
    
    commision_page = get_pagination(commision_objs, 20, page)
    content = {
        'commision_list': commision_page,
        'commision_resume': resume_commision,
    }

    return render(request, 'dashboard/pg_commision.html', content)


# USER LIST VIEW
@login_required
@user_is_agen
def user_profile_view(request):
    """
        Profile list related agen
        Search profile
        Pagination
    """
    page = request.GET.get('page', 1)
    q = request.GET.get('q', None)

    profile_objs = Profile.objects.select_related(
        'wallet'
    ).order_by('user__username')

    if not request.user.is_superuser:
        # Profile related agen
        profile_objs = profile_objs.filter(
            agen = request.user
        )
    
    if q:
        # Search profile
        profile_objs = profile_objs.annotate(
            search = SearchVector(
                'user__username', 'user__email', 'user__first_name', 'user__last_name'
            )
        ).filter(search=q)
    
    # Pagination
    profile_list = get_pagination(profile_objs, 20, page)

    content = {
        'profile_list': profile_list
    }
    return render(request, 'dashboard/pg-user.html', content)


# PROFIL DETAIL
@login_required
@user_is_agen
@user_is_related_agen
def user_profile_detail_view(request, id):
    profile_obj = get_object_or_404(Profile, pk=id)
    sum_loan = LoanRecord.objects.filter(
        user__profile__id=profile_obj.id
    )
    if not request.user.is_superuser:
        sum_loan = sum_loan.filter(
            agen = request.user
        )

    sum_loan = sum_loan.aggregate(
        t = Sum(F('credit')-F('debit'))
    )

    content = {
        'profile': profile_obj,
        'loan': sum_loan,
    }
    return render(request, 'dashboard/pg-user-detail.html', content)


# SALE PROFILE
@login_required
@user_is_agen
@user_is_related_agen
def json_user_billing_view(request, id):
    data = dict()
    page = request.GET.get('page', 1)
    profile_obj = get_object_or_404(Profile, pk=id)

    bill_objs = profile_obj.user.billingrecord_set.filter(
        sequence = 1
    ).filter(
        Q(instansale_trx__isnull=False) | Q(ppobsale_trx__isnull=False) 
    )

    bill_list = get_pagination(bill_objs, page=page)

    content = {
        'bill_list': bill_list
    }
    
    data['html'] = render_to_string(
        'dashboard/includes/partial-user-billing.html', content, request=request
    )
    return JsonResponse(data)


# COMMISION PROFILE
@login_required
@user_is_agen
@user_is_related_agen
def json_user_commision_view(request, id):
    data = dict()
    page = request.GET.get('page', 1)

    profile_obj = get_object_or_404(Profile, pk=id)
    
    commision_objs = CommisionRecord.objects.select_related(
        'instansale_trx', 'ppobsale_trx'
    ).filter(
        agen = request.user
    ).filter(
        Q(instansale_trx__create_by__profile__id=profile_obj.id) | Q(ppobsale_trx__create_by__profile__id=profile_obj.id)
    )

    # PAGINATION METHOD
    commision_list = get_pagination(commision_objs, page=page)
    
    content = {
        'commision_list': commision_list,
    }

    data['html'] = render_to_string(
        'dashboard/includes/partial-user-commision.html', content,
        request=request
    )
    return JsonResponse(data)


# LOAN PROFILE
@login_required
@user_is_agen
@user_is_related_agen
def json_user_loan_view(request, id):
    data = dict()
    page = request.GET.get('page', 1)
    profile_obj = get_object_or_404(
        Profile, pk=id
    )

    loan_objs = LoanRecord.objects.filter(
        user__profile__id=profile_obj.id, agen=request.user, is_paid=False
    ).annotate(
        trx = Case(
            When(instansale_trx__isnull=False, then=F('instansale_trx')),
            When(ppobsale_trx__isnull=False, then=F('ppobsale_trx')),
            default=F('loan_payment')
        )
    )

    # PAGINATION METHOD
    loan_list = get_pagination(loan_objs, page=page)
    content = {
        'loan_list': loan_list
    }

    data['html'] = render_to_string(
        'dashboard/includes/partial-user-loan.html', content,
        request=request
    )
    return JsonResponse(data)

templates/dashboard/base.html
{% extends 'base.html' %}

{% block css %}
<style>
.full.height {
    display: flex;
    flex-direction: row;
}
.full.height > .toc {
    position: fixed;
    z-index: 1;
    width: 250px;
    flex: 0 0 auto;
    -webkit-box-flex: 0;
    background-color: #00b5ad;
    min-height: 2000px;
}
.full.height > .article {
    flex: 1 1 auto;
    margin-left: 250px;
    min-width: 0px;
}
</style>
{% endblock %}

{% block content %}
    <div class="ui vertical inverted sidebar menu left">
        <div class="item">
            <div class="ui basic center aligned segment">
                <h4 class="ui icon inverted  header">
                    <i class="apple icon"></i>
                    Warungid
                </h4>
            </div>
        </div>
        <a href="{% url 'dashboard:sale_list' %}" class="item">
            <i class="telegram icon"></i>
            Sale
        </a>
        <a href="#" class="item">
            <i class="git icon"></i>
            Member
        </a>
    </div>
    <div class="pusher">
        <div class="full height">
            <div class="toc">
                <div class="ui vertical inverted teal fluid large menu">
                    <div class="item">
                        <h4 class="ui icon inverted  header">
                            <i class="apple icon"></i>
                            Warungid
                        </h4>
                    </div>
                    <a href="{% url 'dashboard:index' %}" class="item">
                        <i class="chart line icon"></i>
                        Dashboard
                    </a>
                    <a href="{% url 'dashboard:product_list' %}" class="item">
                        <i class="shopping cart icon"></i>
                        Product
                    </a>
                    <a href="{% url 'dashboard:getme' %}" class="item">
                        <i class="id badge outline icon"></i>
                        Manage Profile
                    </a>
                    <a href="{% url 'dashboard:sale_list' %}" class="item">
                        <i class="dollar sign icon"></i>
                        Transaction
                    </a>
                    
                    <div class="item">
                        <div class="header">
                            Agen
                        </div>
                        <div class="menu">
                            <a href="{% url 'dashboard:commision_list' %}" class="item">
                                Commision
                            </a>
                            <a href="{% url 'dashboard:loan_list' %}" class="item">
                                Loan
                            </a>
                            <a href="{% url 'dashboard:member_list' %}" class="item">
                                <!-- <i class="git icon"></i> -->
                                Members
                            </a>
                        </div>
                    </div>
                   <a href="{% url 'logout' %}" class="item">
                       <i class="power icon"></i>
                       Logout
                   </a>
                </div>
            </div>
            <div class="article">
                <div class="ui vertical basic segment">
                    {% block dash_content %}
                    <!-- Content -->
                    {% endblock %}
                </div>
            </div>
        </div>
        
    </div>
{% endblock %}

templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load humanize %}

{% block title %}
    Dashboard | Warungid - Serasa Warung Milik Sendiri
{% endblock %}

{% block dash_content %}
<div class="ui fluid container">
    <div class="ui stackable horizontally padded vertically divided grid">
        <div class="row">
            <div class="column">
                <h1 class="ui grey header">
                    <i class="chart line icon"></i>
                    <div class="content">
                        Dashboard
                        <div class="sub header">
                            Beranda
                        </div>
                    </div>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="column">
                <div class="ui card">
                    <div class="content">
                        <div class="header">
                            {{ request.user.profile.get_fullname|title }}
                        </div>
                        <div class="description">
                            Hai {{ request.user.first_name }}, selamat datang di dashboard.
                        </div>
                    </div>
                </div>

                <div class="ui tiny teal statistic">
                    <div class="label">Saldo</div>
                    <div class="value">{{ user.profile.wallet.get_saldo|floatformat:0|intcomma }}</div>
                </div>
                <div class="ui tiny purple statistic">
                    <div class="label">Commision</div>
                    <div class="value">{{ user.profile.wallet.commision|floatformat:0|intcomma }}</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="ten wide column">
                <div class="ui segment">
                    <div class="ui placeholder">
                        <div class="image header">
                            <div class="content">
                                <div class="line"></div>
                                <div class="line"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="ui clearing segment">
                    <h4 class="ui left floated header">
                        TRANSACTION RATE
                    </h4>
                </div>
            </div>
            <div class="six wide column">
                <div class="ui segment">
                    <div class="ui small feed">
                        {% for i in commision_list %}
                        <div class="event">
                            <div class="content">
                                <div class="extra text">
                                    <a>{{ i.get_trx }}</a> <br>Earning {{ i.debit|floatformat:0|intcomma }} from  {{ i.get_trx.product.product_name|title }}
                                </div>
                                <div class="meta">
                                    <div class="like">
                                        {{ i.timestamp|naturaltime }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                        No Commision
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/pg-getme.html
{% extends 'dashboard/base.html' %}

{% block title %}
My Profile
{% endblock %}

{% block dash_content %}

{% endblock %}

templates/dashboard/pg-loan.html
{% extends 'dashboard/base.html' %}
{% load humanize %}

{% block title %}
Loan
{% endblock %}

{% block dash_content %}
<div class="ui fluid container">
    <div class="ui horizontally padded stackable vertically divided grid">
        <div class="row">
            <div class="column">
                <h1 class="ui header">
                    Loan
                    <div class="sub header">
                        Piutang Member
                    </div>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="column">
                <div class="ui text menu">
                    <form action="" class="ui form item">
                        <div class="field">
                            <div class="ui right icon input">
                                <i class="search icon"></i>
                                <input type="text" name="q" placeholder="Search..." style="border-radius:20px">
                            </div>
                        </div>
                    </form>
                </div>
                <table class="ui small table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Info Trx</th>
                            <th>Loan</th>
                            <th>Payment</th>
                            <th>Create by</th>
                            <th>Create on</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in loan_list %}
                        <tr>
                            <td>{{ forloop.counter0|add:loan_list.start_index }}</td>
                            <td>
                                <div class="ui list">
                                    <div class="content">
                                        <a class="header">{{ i.bill_record.get_trx.code }}</a>
                                        <div class="description">{{ i.bill_record.get_trx.product.product_name }}</div>
                                    </div>
                                </div>
                            </td>
                            <td>
                                {{ i.debit|floatformat:0|intcomma }}
                            </td>
                            <td>
                                {{ i.credit|floatformat:0|intcomma }}
                            </td>
                            <td>
                                {{ i.user.email }}
                            </td>
                            <td>
                                {{ i.timestamp|date:"d/m/Y H:i" }}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <!-- Pagination -->
                {% include 'pagination.html' with objs=loan_list %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/pg-product.html
{% extends 'dashboard/base.html' %}
{% load humanize %}

{% block title %}
Product
{% endblock %}

{% block dash_content %}
<div class="ui fluid container">
    <div class="ui stackabel horizontally padded vertically divided grid">
        <div class="row">
            <div class="column">
                <h1 class="ui grey header">
                    <i class="coffee icon"></i>
                    <div class="content">
                        Product
                        <div class="sub header">
                            Produk    
                        </div>
                    </div>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="three wide column">
                <div class="ui fluid vertical accordion menu" id="sidemenu-product">
                    {% for i in group_list %}
                    <div class="item">
                        <div class="title {% if forloop.counter == 1%} active {% endif %}">
                            <i class="dropdown icon"></i>
                            {{ i.group_name }}
                        </div>
                        <div class="content {% if forloop.counter == 1%} active {% endif %}">
                            <div class="menu">
                                {% for o in i.operator_set.distinct %}
                                <a href="#" target-url="{% url 'dashboard:json_products' %}?gr={{ i.id }}&op={{ o.id }}" class="item js-product">
                                    {{ o.operator_name }}
                                </a>
                                {% endfor %}
                            </div> 
                        </div>
                    </div>
                    {% endfor %}
                </div>
                
            </div>
            <div class="thirteen wide column">
                <div id="table-id" class="ui very relaxed divided list">
                    {% for i in product_list %}
                    <div class="item">
                        <div class="right floated content">
                            <div class="ui left pointing basic green label">
                                {% if i.price == 0 %}
                                    Depend Inquery
                                {% else %}
                                    IDR {{ i.price|intcomma }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="content">
                            <div class="header">
                                # {{ i.code }}
                            </div>
                            <p>
                                {{ i.product_name }}
                            </p>
                            <div class="meta">
                                <i class="ui small {% if i.is_active %} green {% else %} red {% endif %} label">{% if i.is_active %} Active {% else %} Closed {% endif %}</i>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $(document).ready(function() {
        var load_table = function() {
            var btn = $(this);
            $.ajax({
                url: btn.attr('target-url'),
                dataType: 'json',
                success: function(data) {
                    $('#table-id').html(data.html);
                }
            });
            return false;
        }

        $('#sidemenu-product a').click(load_table);
    });
</script>
{% endblock %}

templates/dashboard/pg-user.html
{% extends 'dashboard/base.html' %}
{% load humanize %}

{% block title %}
    Members | Warungid
{% endblock %}

{% block dash_content %}
<div class="ui fluid container">
    <div class="ui stackable horizontally padded vertically divided grid">
        <div class="row">
            <div class="column">
                <h1 class="ui header">
                    Member
                    <div class="sub header">
                        Anggota
                    </div>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="column">
                <div class="ui text menu">
                    <form action="" class="ui form item">
                        <div class="field">
                            <div class="ui right icon input">
                                <i class="search icon"></i>
                                <input type="text" name="q" placeholder="Search..." style="border-radius:20px">
                            </div>
                        </div>
                    </form>
                </div>
                <table class="ui small bottom attached table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>User</th>
                            <th>Ponsel</th>
                            <th>Active</th>
                            <th>Saldo</th>
                            <th>Commision</th>
                            <th>Loan</th>
                            <th>Limit</th>
                        </tr>
                    </thead>
                    {% for profile in profile_list %}
                    <tr onclick="window.location.href='{% url 'dashboard:profile' profile.id %}'">
                        <td>{{ profile_list.start_index|add:forloop.counter0 }}</td>
                        <td>
                            <div class="ui list">
                                <div class="item">
                                    <div class="content">
                                        <a class="header">
                                            {{ profile.get_fullname|title }}
                                        </a>
                                        <div class="description">
                                            {{ profile.user.email }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td>{{ profile.get_hidden_ponsel|default:'-' }}</td>
                        <td>
                            {% if profile.user.is_active %}
                            <i class="green check icon"></i>
                            {% else %}
                            <i class="red close icon"></i>
                            {% endif %}
                        </td>
                        <td>{{ profile.wallet.get_saldo|floatformat:0|intcomma }}</td>
                        <td>{{ profile.wallet.commision|floatformat:0|intcomma }}</td>
                        <td class="negative">{{ profile.wallet.get_loan|floatformat:0|intcomma }}</td>
                        <td>{{ profile.wallet.limit|floatformat:0|intcomma }}</td>
                    </tr>
                    {% endfor %}
                </table>

                <!-- Pagination -->
                {% include 'pagination.html' with objs=profile_list %}

            </div>
        </div>
    </div>
</div>
{% endblock %}